"""initial

Revision ID: 6399e5f0f61f
Revises: 
Create Date: 2026-09-11 03:11:38.911540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6399e5f0f61f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_email'), 'accounts_user', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_user_username'), 'accounts_user', ['username'], unique=True)
    op.create_table('accounts_apitoken',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_apitoken_digest'), 'accounts_apitoken', ['digest'], unique=True)
    op.create_index(op.f('ix_accounts_apitoken_prefix'), 'accounts_apitoken', ['prefix'], unique=False)
    op.create_index(op.f('ix_accounts_apitoken_user_id'), 'accounts_apitoken', ['user_id'], unique=False)
    op.create_table('workspaces_workspace',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_workspace_created_by_id'), 'workspaces_workspace', ['created_by_id'], unique=False)
    op.create_table('tables_datatable',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('db_table_name', sa.String(length=63), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces_workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_datatable_db_table_name'), 'tables_datatable', ['db_table_name'], unique=True)
    op.create_index(op.f('ix_tables_datatable_workspace_id'), 'tables_datatable', ['workspace_id'], unique=False)
    op.create_table('workspaces_workspacemember',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='workspacerole'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces_workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uniq_workspace_member')
    )
    op.create_index(op.f('ix_workspaces_workspacemember_user_id'), 'workspaces_workspacemember', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspaces_workspacemember_workspace_id'), 'workspaces_workspacemember', ['workspace_id'], unique=False)
    op.create_table('tables_datafield',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('db_column_name', sa.String(length=63), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['table_id'], ['tables_datatable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uniq_table_field_name')
    )
    op.create_index(op.f('ix_tables_datafield_db_column_name'), 'tables_datafield', ['db_column_name'], unique=True)
    op.create_index(op.f('ix_tables_datafield_table_id'), 'tables_datafield', ['table_id'], unique=False)
    op.create_table('tables_dataview',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('view_type', sa.String(length=32), nullable=False),
    sa.Column('filter_type', sa.String(length=3), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('sortings', sa.JSON(), nullable=False),
    sa.Column('field_options', sa.JSON(), nullable=False),
    sa.Column('field_order', sa.JSON(), nullable=False),
    sa.Column('view_options', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables_datatable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uniq_table_view_name')
    )
    op.create_index(op.f('ix_tables_dataview_owner_id'), 'tables_dataview', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tables_dataview_table_id'), 'tables_dataview', ['table_id'], unique=False)
    op.create_table('tables_tablepermission',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('read_role', sa.String(length=16), nullable=False),
    sa.Column('edit_records_role', sa.String(length=16), nullable=False),
    sa.Column('edit_views_role', sa.String(length=16), nullable=False),
    sa.Column('edit_schema_role', sa.String(length=16), nullable=False),
    sa.Column('comment_role', sa.String(length=16), nullable=False),
    sa.Column('hidden_fields', sa.JSON(), nullable=False),
    sa.Column('row_filters', sa.JSON(), nullable=False),
    sa.Column('row_filter_type', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['table_id'], ['tables_datatable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_tablepermission_table_id'), 'tables_tablepermission', ['table_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_tablepermission_table_id'), table_name='tables_tablepermission')
    op.drop_table('tables_tablepermission')
    op.drop_index(op.f('ix_tables_dataview_table_id'), table_name='tables_dataview')
    op.drop_index(op.f('ix_tables_dataview_owner_id'), table_name='tables_dataview')
    op.drop_table('tables_dataview')
    op.drop_index(op.f('ix_tables_datafield_table_id'), table_name='tables_datafield')
    op.drop_index(op.f('ix_tables_datafield_db_column_name'), table_name='tables_datafield')
    op.drop_table('tables_datafield')
    op.drop_index(op.f('ix_workspaces_workspacemember_workspace_id'), table_name='workspaces_workspacemember')
    op.drop_index(op.f('ix_workspaces_workspacemember_user_id'), table_name='workspaces_workspacemember')
    op.drop_table('workspaces_workspacemember')
    op.drop_index(op.f('ix_tables_datatable_workspace_id'), table_name='tables_datatable')
    op.drop_index(op.f('ix_tables_datatable_db_table_name'), table_name='tables_datatable')
    op.drop_table('tables_datatable')
    op.drop_index(op.f('ix_workspaces_workspace_created_by_id'), table_name='workspaces_workspace')
    op.drop_table('workspaces_workspace')
    op.drop_index(op.f('ix_accounts_apitoken_user_id'), table_name='accounts_apitoken')
    op.drop_index(op.f('ix_accounts_apitoken_prefix'), table_name='accounts_apitoken')
    op.drop_index(op.f('ix_accounts_apitoken_digest'), table_name='accounts_apitoken')
    op.drop_table('accounts_apitoken')
    op.drop_index(op.f('ix_accounts_user_username'), table_name='accounts_user')
    op.drop_index(op.f('ix_accounts_user_email'), table_name='accounts_user')
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
