# Generated by Django 5.2.17 on 2026-09-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('prefix', models.CharField(editable=False, max_length=12, verbose_name='令牌前缀')),
                ('digest', models.CharField(editable=False, max_length=64, unique=True, verbose_name='令牌摘要')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_on', models.DateTimeField(blank=True, null=True, verbose_name='最近使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'API 令牌',
                'verbose_name_plural': 'API 令牌',
                'ordering': ['-created_on'],
            },
        ),
    ]
