# Generated by Django 5.2.17 on 2026-09-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='表名')),
                ('db_table_name', models.CharField(editable=False, max_length=63, unique=True, verbose_name='物理表名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('trashed', models.BooleanField(default=False, verbose_name='回收站')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='workspaces.workspace', verbose_name='所属工作区')),
            ],
            options={
                'verbose_name': '数据表',
                'verbose_name_plural': '数据表',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='字段名')),
                ('field_type', models.CharField(max_length=32, verbose_name='字段类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='字段配置')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('trashed', models.BooleanField(default=False, verbose_name='回收站')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tables.datatable', verbose_name='所属数据表')),
            ],
            options={
                'verbose_name': '数据字段',
                'verbose_name_plural': '数据字段',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('table', 'name'), name='uniq_table_field_name')],
            },
        ),
    ]
