# Generated by Django 5.2.17 on 2026-09-01 12:46

import cndb.tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='db_column_name',
            field=models.CharField(default=cndb.tables.models.generate_db_column_name, editable=False, max_length=63, verbose_name='物理列名'),
        ),
    ]
