# Generated by Django 5.2.17 on 2026-09-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_datafield_db_column_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='视图名')),
                ('view_type', models.CharField(choices=[('grid', '表格'), ('kanban', '看板'), ('calendar', '日历'), ('gallery', '画册'), ('form', '表单')], default='grid', max_length=32, verbose_name='视图形态')),
                ('filter_type', models.CharField(choices=[('AND', '全部满足'), ('OR', '任一满足')], default='AND', max_length=3, verbose_name='条件组合')),
                ('filters', models.JSONField(blank=True, default=list, verbose_name='筛选规则')),
                ('sortings', models.JSONField(blank=True, default=list, verbose_name='排序规则')),
                ('field_options', models.JSONField(blank=True, default=dict, verbose_name='字段选项')),
                ('public', models.BooleanField(default=False, verbose_name='公开共享')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tables.datatable', verbose_name='所属数据表')),
            ],
            options={
                'verbose_name': '数据视图',
                'verbose_name_plural': '数据视图',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('table', 'name'), name='uniq_table_view_name')],
            },
        ),
    ]
