# Generated by Django 5.2.17 on 2026-09-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_dataview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_role', models.CharField(blank=True, default='', max_length=16, verbose_name='读取最低角色')),
                ('edit_records_role', models.CharField(blank=True, default='', max_length=16, verbose_name='行数据编辑最低角色')),
                ('edit_views_role', models.CharField(blank=True, default='', max_length=16, verbose_name='视图编辑最低角色')),
                ('edit_schema_role', models.CharField(blank=True, default='', max_length=16, verbose_name='结构编辑最低角色')),
                ('hidden_fields', models.JSONField(blank=True, default=dict, verbose_name='字段级隐藏')),
                ('row_filters', models.JSONField(blank=True, default=list, verbose_name='行级过滤规则')),
                ('row_filter_type', models.CharField(default='AND', max_length=3, verbose_name='行级条件组合')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='tables.datatable', verbose_name='所属数据表')),
            ],
            options={
                'verbose_name': '表级权限',
                'verbose_name_plural': '表级权限',
            },
        ),
    ]
