# Generated by Django 5.2.17 on 2026-09-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tablepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataview',
            name='form_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='表单配置'),
        ),
        migrations.AddField(
            model_name='dataview',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='公开标识'),
        ),
    ]
