"""tables 插件 Pydantic schemas（facade —— 只做导入导出）."""

from __future__ import annotations

from cndb.plugins.tables.schemas.governance import (
    CleanAction,
    CleanRequest,
    DetectRequest,
    GovernanceTaskOut,
    MergeGroup,
    MergeRequest,
)
from cndb.plugins.tables.schemas.models import (
    BulkDeleteRequest,
    FieldCreate,
    FieldImportRequest,
    FieldImportResponse,
    FieldResponse,
    FieldUpdate,
    MemberCreate,
    MemberOut,
    MemberUpdate,
    OwnerBrief,
    OwnerTransfer,
    PermissionCreate,
    PermissionResponse,
    PermissionUpdate,
    RecordCreate,
    RecordListRequest,
    RecordListResponse,
    RecordUpdate,
    TableCreate,
    TableDetailResponse,
    TableOwnerBrief,
    TableResponse,
    TableUpdate,
    ViewBrief,
    ViewCreate,
    ViewResponse,
    ViewUpdate,
    WorkspaceBrief,
)

__all__ = [
    "BulkDeleteRequest",
    "CleanAction",
    "CleanRequest",
    "DetectRequest",
    "FieldCreate",
    "FieldImportRequest",
    "FieldImportResponse",
    "FieldResponse",
    "FieldUpdate",
    "GovernanceTaskOut",
    "MemberCreate",
    "MemberOut",
    "MemberUpdate",
    "MergeGroup",
    "MergeRequest",
    "OwnerBrief",
    "OwnerTransfer",
    "PermissionCreate",
    "PermissionResponse",
    "PermissionUpdate",
    "RecordCreate",
    "RecordListRequest",
    "RecordListResponse",
    "RecordUpdate",
    "TableCreate",
    "TableDetailResponse",
    "TableOwnerBrief",
    "TableResponse",
    "TableUpdate",
    "ViewBrief",
    "ViewCreate",
    "ViewResponse",
    "ViewUpdate",
    "WorkspaceBrief",
]
