# Generated by Django 5.2.17 on 2026-09-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工作区',
                'verbose_name_plural': '工作区',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('editor', '编辑者'), ('commenter', '评论者'), ('viewer', '查看者')], default='viewer', max_length=16, verbose_name='角色')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace', verbose_name='工作区')),
            ],
            options={
                'verbose_name': '工作区成员',
                'verbose_name_plural': '工作区成员',
                'ordering': ['workspace', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_workspace_member')],
            },
        ),
    ]
